package sinosoft.com.ribbon.clienta.dto.vue1;

import java.util.Date;
import com.fasterxml.jackson.annotation.JsonFormat;


public class TestDb1 {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testdb1.RiskCode
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    private String riskcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testdb1.RiskName
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    private String riskname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testdb1.DbCode
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    private Integer dbcode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testdb1.MakeTime
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date maketime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column testdb1.ModifyTime
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    @JsonFormat(pattern = "yyyy-MM-dd HH:mm:ss")
    private Date modifytime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testdb1.RiskCode
     *
     * @return the value of testdb1.RiskCode
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    public String getRiskcode() {
        return riskcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testdb1.RiskCode
     *
     * @param riskcode the value for testdb1.RiskCode
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    public void setRiskcode(String riskcode) {
        this.riskcode = riskcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testdb1.RiskName
     *
     * @return the value of testdb1.RiskName
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    public String getRiskname() {
        return riskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testdb1.RiskName
     *
     * @param riskname the value for testdb1.RiskName
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    public void setRiskname(String riskname) {
        this.riskname = riskname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testdb1.DbCode
     *
     * @return the value of testdb1.DbCode
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    public Integer getDbcode() {
        return dbcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testdb1.DbCode
     *
     * @param dbcode the value for testdb1.DbCode
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    public void setDbcode(Integer dbcode) {
        this.dbcode = dbcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testdb1.MakeTime
     *
     * @return the value of testdb1.MakeTime
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    public Date getMaketime() {
        return maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testdb1.MakeTime
     *
     * @param maketime the value for testdb1.MakeTime
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    public void setMaketime(Date maketime) {
        this.maketime = maketime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column testdb1.ModifyTime
     *
     * @return the value of testdb1.ModifyTime
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    public Date getModifytime() {
        return modifytime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column testdb1.ModifyTime
     *
     * @param modifytime the value for testdb1.ModifyTime
     *
     * @mbggenerated Sun May 19 21:54:40 CST 2019
     */
    public void setModifytime(Date modifytime) {
        this.modifytime = modifytime;
    }
}